# Dependabot config
# - Automatically checks for outdated dependencies and open pull requests to update them.

version: 2
updates:
  # Check GitHub Actions used by this repo.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    # Control the commit message and PR title format that Dependabot uses.
    commit-message:
      prefix: "[dependabot]"
      # Include the dependency scope in the title/message when possible.
      include: "scope"
    # Group GitHub Actions updates into a single PR.
    # - This reduces the number of Dependabot PRs you have to review.
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"

  # Check Dockerfiles used by this repository.
  - package-ecosystem: "docker"
    directories:
      - "/utils/kcBlog"
      - "/utils/kcDevContainer"
      - "/utils/kcRepoScanner"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[dependabot]"
      include: "scope"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Check Python dependencies used by kcBlog.
  - package-ecosystem: "pip"
    directory: "/utils/kcBlog/app"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[dependabot]"
      include: "scope"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
