---
version: 2

# Dependabot config
# - Automatically checks for outdated dependencies and opens pull requests.

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "deps:"
      include: "scope"
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directories:
      - "/utils/kcAudioTranscribe"
      - "/utils/kcBlog"
      - "/utils/kcDevContainer"
      - "/utils/kcRepoScanner"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "deps:"
      include: "scope"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directories:
      - "/utils/kcBlog"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "deps:"
      include: "scope"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
