# syntax=docker/dockerfile:1

#| # kcDevContainer
#|   
#| `kcDevContainer` is standardized Docker development environment container.   
#|   
#| ## Setup  
#|   
#| ```sh
#| make build
#| ```  
#|   
#| ## Usage  
#|
#| Run and enter the container's shell:
#| ```sh
#| make run
#| ```  

#| ## Example
#| ![kcDevContainer demo image](./demo.gif)

FROM debian:latest AS base-layer

RUN apt-get update && apt-get install -y curl

# ---

FROM base-layer AS dependencies-layer

# Install system packages
COPY ./config/install-system.sh .
RUN sh ./install-system.sh; rm -f ./install-system.sh

# Create a non-root user that matches the host user's ID
ARG kcUserId=1000
ARG kcGroupId=1000
RUN <<EOT
  groupadd -g $kcGroupId user
  useradd -m -u $kcUserId -g $kcGroupId user
  chsh -s $(which zsh) user
EOT
USER user
WORKDIR /home/user

# Install user packages
COPY --chown=user:user ./config/user-files/* ./
COPY --chown=user:user ./config/install-user.sh .
RUN sh ./install-user.sh; rm -f ./install-user.sh

# ---

FROM dependencies-layer AS built-image

# Enter the container with a shell:
CMD ["/bin/zsh", "-l"]