# syntax=docker/dockerfile:1

FROM debian:stable AS base-base

RUN apt-get update && apt-get install -y curl

# ---

FROM base-base AS dependencies-base

# Install system packages
COPY ./config/install-system.sh .
RUN sh ./install-system.sh; rm -f ./install-system.sh

# Create a non-root user that matches the host user's ID
ARG kcUserId=1000
ARG kcGroupId=1000
RUN <<EOT
  groupadd -g $kcGroupId user
  useradd -m -u $kcUserId -g $kcGroupId user
  chsh -s $(which zsh) user
EOT
USER user
WORKDIR /home/user

# Install user packages
COPY --chown=user:user ./config/user-files/* ./
COPY --chown=user:user ./config/install-user.sh .
RUN sh ./install-user.sh; rm -f ./install-user.sh

# ---

FROM dependencies-base AS built-image

WORKDIR /home/user/workdir

# Enter the container with a shell:
CMD ["/bin/zsh", "-l"]